

europe = {
    "Amsterdam": "Netherlands",
    "Andorra la Vella": "Andorra",
    "Athens": "Greece",
    "Belgrade": "Serbia",
    "Berlin": "Germany",
    "Bern": "Switzerland",
    "Bratislava": "Slovakia",
    "Brussels": "Belgium",
    "Bucharest": "Romania",
    "Budapest": "Hungary",
    "Chisinau": "Moldova",
    "Copenhagen": "Denmark",
    "Dublin": "Ireland",
    "Helsinki": "Finland",
    "Kiev": "Ukraine",
    "Lisbon": "Portugal",
    "Ljubljana": "Slovenia",
    "London": "United Kingdom",
    "Luxembourg": "Luxembourg",
    "Madrid": "Spain",
    "Minsk": "Belarus",
    "Monaco": "Monaco",
    "Moscow": "Russia",
    "Nicosia": "Cyprus",
    "Nuuk": "Greenland",
    "Oslo": "Norway",
    "Paris": "France",
    "Podgorica": "Montenegro",
    "Prague": "Czech Republic",
    "Reykjavik": "Iceland",
    "Riga": "Latvia",
    "Rome": "Italy",
    "San Marino": "San Marino",
    "Sarajevo": "Bosnia & Herzegovina",
    "Skopje": "Macedonia",
    "Sofia": "Bulgaria",
    "Stockholm": "Sweden",
    "Tallinn": "Estonia",
    "Tirana": "Albania",
    "Vaduz": "Liechtenstein",
    "Valletta": "Malta",
    "Vatican City": "Holy See",
    "Vienna": "Austria",
    "Vilnius": "Lithuania",
    "Warsaw": "Poland",
    "Zagreb": "Croatia",
}

united_states = {
    "Alabama": "Montgomery",
    "Alaska": "Juneau",
    "Arizona": "Phoenix",
    "Arkansas": "Little Rock",
    "California": "Sacramento",
    "Colorado": "Denver",
    "Connecticut": "Hartford",
    "Delaware": "Dover",
    "Florida": "Tallahassee",
    "Georgia": "Atlanta",
    "Hawaii": "Honolulu",
    "Idaho": "Boise",
    "Illinois": "Springfield",
    "Indiana": "Indianapolis",
    "Iowa": "Des Moines",
    "Kansas": "Topeka",
    "Kentucky": "Frankfort",
    "Louisiana": "Baton Rouge",
    "Maine": "Augusta",
    "Maryland": "Annapolis",
    "Massachusetts": "Boston",
    "Michigan": "Lansing",
    "Minnesota": "Saint Paul",
    "Mississippi": "Jackson",
    "Missouri": "Jefferson City",
    "Montana": "Helena",
    "Nebraska": "Lincoln",
    "Nevada": "Carson City",
    "New Hampshire": "Concord",
    "New Jersey": "Trenton",
    "New Mexico": "Santa Fe",
    "New York": "Albany",
    "North Carolina": "Raleigh",
    "North Dakota": "Bismarck",
    "Ohio": "Columbus",
    "Oklahoma": "Oklahoma City",
    "Oregon": "Salem",
    "Pennsylvania": "Harrisburg",
    "Rhode Island": "Providence",
    "South Carolina": "Columbia",
    "South Dakota": "Pierre",
    "Tennessee": "Nashville",
    "Texas": "Austin",
    "Utah": "Salt Lake City",
    "Vermont": "Montpelier",
    "Virginia": "Richmond",
    "Washington": "Olympia",
    "West Virginia": "Charleston",
    "Wisconsin": "Madison",
    "Wyoming": "Cheyenne",
}